{
    'derived_from' : 'jwst_miri_distortion_0001.rmap',
    'file_ext' : '.json',
    'filekind' : 'DISTORTION',
    'filetype' : 'DISTORTION',
    'instrument' : 'MIRI',
    'mapping' : 'REFERENCE',
    'name' : 'jwst_miri_distortion_0002.rmap',
    'observatory' : 'JWST',
    'parkey' : (('META.INSTRUMENT.DETECTOR', 'META.INSTRUMENT.CHANNEL', 'META.INSTRUMENT.BAND'),),
    'reference_to_dataset' : {'BAND': 'META.INSTRUMENT.BAND', 'DETECTOR': 'META.INSTRUMENT.DETECTOR', 'CHANNEL': 'META.INSTRUMENT.CHANNEL'},
    'sha1sum' : 'e33265823224a35bab99d368fd22f33a31471845',
    'suffix' : 'distortion',
    'text_descr' : 'Distortion',
}
