{
    'derived_from' : 'cloning tool 0.05b (2013-04-12) used on 2013-09-04',
    'file_ext' : '.fits',
    'filekind' : 'PHOTOM',
    'filetype' : 'PHOTOMETRIC CALIBRATION',
    'instrument' : 'NIRCAM',
    'mapping' : 'REFERENCE',
    'name' : 'jwst_nircam_photom_0001.rmap',
    'observatory' : 'JWST',
    'parkey' : (('META.INSTRUMENT.DETECTOR', 'META.INSTRUMENT.FILTER'),),
    'sha1sum' : '8b882aefccecf7de1ae321e78052f74cf84b164f',
    'suffix' : 'photom',
    'text_descr' : 'Absolute Calibration',
    'unique_rowkeys': ('FILTER', 'PUPIL', 'ORDER'),
}
