{
    'derived_from' : 'jwst_nirspec_specwcs_0002.rmap',
    'extra_keys' : ('META.EXPOSURE.TYPE',),
    'file_ext' : '.json',
    'filekind' : 'SPECWCS',
    'filetype' : 'SPECWCS',
    'instrument' : 'NIRSPEC',
    'mapping' : 'REFERENCE',
    'name' : 'jwst_nirspec_specwcs_0003.rmap',
    'observatory' : 'JWST',
    'parkey' : (('META.INSTRUMENT.DETECTOR',),),
    'reference_to_dataset' : {'DETECTOR': 'META.INSTRUMENT.DETECTOR'},
    'rmap_relevance' : '(META.EXPOSURE.TYPE not in ("MIR_IMAGE", "NRC_IMAGE", "NIS_IMAGE"))',
    'sha1sum' : 'f0a3fb1ba255cc02307e9b33beacf371f5df991a',
    'suffix' : 'specwcs',
    'text_descr' : 'Spectroscopic World Coordinate System',
}
