#! /bin/csh

cd `dirname $0`

if ( "$*" == "" ) then
    set dirs="crds"
else
    set dirs="$*"
endif 

if (-e ../CRDS_server) then
    set dirs="$dirs ../CRDS_server/sources"
endif

foreach pat ('*.orig' '*.pyc' 'build')
	find ${dirs} -name "${pat}" | xargs rm -rf
end

rm -rf dist MANIFEST
rm -rf build
