#! /bin/csh

cd `dirname $0`

set dirs="crds"

if (-e ../CRDS_server) then
	set dirs="$dirs ../CRDS_server"
endif

foreach pat ('*.orig' '*.pyc' 'build')
	find ${dirs} -name "${pat}" | xargs rm -rf
end

rm -rf dist MANIFEST
