#! /bin/bash

if [ "$1" == "os-x" ]; then
    export CONDA_INSTALLER=Miniconda3-latest-MacOSX-x86_64.sh
elif [ "$1" == "linux" ]; then
    export CONDA_INSTALLER=Miniconda3-latest-Linux-x86_64.sh
else
    echo "usage:  crds_setup_env  [os-x|linux]"
    exit -1
fi
echo "Installing $CONDA_INSTALLER"

rm -f ${CONDA_INSTALLER}*
wget --no-check-certificate https://repo.anaconda.com/miniconda/${CONDA_INSTALLER}

bash ${CONDA_INSTALLER}  -b -p $HOME/miniconda3
rm -f ${CONDA_INSTALLER}

conda update --yes -n base -c  conda
conda config --add channels http://ssb.stsci.edu/astroconda
conda create --yes -n crds-env python=3.7 # conda
conda activate crds-env

pip install numpy
pip install git+https://github.com/spacetelescope/jwst

pip uninstall --yes crds
# pip install git+https://github.com/spacetelescope/crds.git#egg=crds["submission","test","dev","docs"]
pip install .["submission","test","dev","docs"]

conda install --yes fitsverify
