#! /bin/sh

cd `dirname $0`

if (test -e clean)
then
    ./clean
fi

rm -f install.log

st=0

if (test -e save_version) 
then 
    ./save_version >crds/git_version.py;  
fi
python setup.py install $* --force  >> install.log
st=$st$?
python setup_data.py install --force >>install.log
st=$st$?

if (test -e clean)
then
    ./clean
fi

echo final status $st
st=`echo $st | tr -d 0 | cut -c1-1`
exit $st
