#! /usr/bin/env python3
import sys
import os
import os.path
import crds.pysh
import crds

os.chdir(os.path.dirname(sys.argv[0]) or ".")
os.environ["CRDS_MAPPATH"] = os.path.join(os.path.dirname(crds.__file__), "cache", "mappings")

crds.pysh.sh("nosetests --verbose --with-doctest --doctest-tests --doctest-options=+IGNORE_EXCEPTION_DETAIL --logging-clear-handlers {}".format(" ".join(sys.argv[1:])))

