#! /usr/bin/env python
import sys
import os
import os.path
import crds.pysh
import crds.mappings

os.chdir(os.path.dirname(sys.argv[0]) or ".")
os.environ["CRDS_MAPPATH"] = os.path.dirname(crds.mappings.__file__)

crds.pysh.sh("nosetests . --with-doctest")



