#! /bin/sh
echo "__version__ = '"`git show -s --pretty=%h`"'"  
echo 
echo "__full_version_info__ = '''" 
echo "branch: `git rev-parse --abbrev-ref HEAD`"
echo "sha1: `git show -s --pretty=%h`"
echo "'''"
