[tool.towncrier]
filename = "CHANGES.rst"
directory = "changes"
package = "crds"
title_format = "{version} ({project_date})"
ignore = ["README.md"]
wrap = true
issue_format = "`#{issue} <https://github.com/spacetelescope/crds/issues/{issue}>`_"

[tool.towncrier.fragment.hst]
name = "HST"

[tool.towncrier.fragment.jwst]
name = "JWST"

[tool.towncrier.fragment.roman]
name = "ROMAN"

[tool.towncrier.fragment.synphot]
name = "synphot"

[tool.towncrier.fragment.doc]
name = "Documentation"

[tool.towncrier.fragment.testing]
name = "Testing / Automation"

[tool.towncrier.fragment.general]

