#! /bin/sh

export VERSION="${1}"
export RATIONALE="${2}"
export REMOTE=${3:-upstream}

export BRANCH="b${VERSION}"

# Exit on failure
set -e
set -o pipefail

git fetch ${REMOTE} --tags
git checkout ${REMOTE}/master
echo "$(git branch)" | grep ${BRANCH} && git branch -D "${BRANCH}"
git checkout -b ${BRANCH}

./save_version "${VERSION}"  "${RATIONALE}"
git add crds/__init__.py
git add crds/core/git_version.py
git add setup.cfg
git add setup.py
git commit -m "Updated version info to ${VERSION}"

git branch -D master
git checkout ${REMOTE}/master
git merge ${BRANCH}
echo "$(git tag)" | grep ${VERSION} && git tag -d ${VERSION}
git tag -a ${VERSION} -m "${RATIONALE}"
git checkout -b master
git push ${REMOTE} master
git push ${REMOTE} --force --tags
