{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'overscan',
    'ld_tpn': 'acs_osc_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'yes',
    'reffile_switch': 'none',
    'rmap_relevance': '(DETECTOR != "SBC")',
    'suffix': 'osc',
    'text_descr': 'Overscan Region Table',
    'tpn': 'acs_osc.tpn',
    'unique_rowkeys': ('CCDCHIP', 'CCDAMP'),
}
