{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'distortion coefficients',
    'ld_tpn': 'acs_idc_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'yes',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'idc',
    'text_descr': 'Image Distortion Correction File',
    'tpn': 'acs_idc.tpn',
    'unique_rowkeys': ('DETCHIP', 'WAVELENGTH', 'DIRECTION', 'FILTER1', 'FILTER2', 'V2REF', 'V3REF'),
}
