{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'multidrizzle parameters',
    'ld_tpn': 'acs_mdz_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'yes',
    'reffile_switch': 'drizcorr',
    'rmap_relevance': '(DRIZCORR != "OMIT")',
    'suffix': 'mdz',
    'text_descr': 'Multidrizzle Parameter Table',
    'tpn': 'acs_mdz.tpn',
    'unique_rowkeys': ('FILTER', 'NUMIMAGES'),
}
