{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'dxy grid',
    'ld_tpn': 'acs_npl_ld.tpn',
    'parkey': ('DETECTOR', 'FILTER1', 'FILTER2'),
    'parkey_relevance': {},
    'reffile_format': 'image',
    'reffile_required': 'no',
    'reffile_switch': 'drizcorr',
    'rmap_relevance': '(DRIZCORR != "OMIT")',
    'suffix': 'npl',
    'text_descr': 'Non-polynomial Offset',
    'tpn': 'acs_npl.tpn',
    'unique_rowkeys': None,
}
