{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'msk',
    'ld_tpn': 'nic_msk_ld.tpn',
    'parkey': ('CAMERA',),
    'parkey_relevance': {},
    'reffile_format': 'image',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'msk',
    'text_descr': 'Static Mask File',
    'tpn': 'nic_msk.tpn',
    'unique_rowkeys': None,
}
