{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'drk',
    'ld_tpn': 'nic_drk_ld.tpn',
    'parkey': ('CAMERA', 'READOUT', 'NREAD', 'SAMP_SEQ', 'OBSMODE'),
    'parkey_relevance': {},
    'reffile_format': 'image',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': '(SAMP_SEQ not in ["SPARS4","SPARS16","SPARS32","SPARS128"])',
    'suffix': 'drk',
    'text_descr': 'Dark Frame',
    'tpn': 'nic_drk.tpn',
    'unique_rowkeys': None,
}
