{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'scn',
    'ld_tpn': 'nic_scn_ld.tpn',
    'parkey': (),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'scn',
    'text_descr': 'SAACLEAN Task Parameters',
    'tpn': 'nic_scn.tpn',
    'unique_rowkeys': ('CAMERA',),
}
