{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'mama linearity table',
    'ld_tpn': 'stis_lin_ld.tpn',
    'parkey': (),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': '(DETECTOR != "CCD")',
    'suffix': 'lin',
    'text_descr': 'Mama Linearity Table',
    'tpn': 'stis_lin.tpn',
    'unique_rowkeys': ('DETECTOR',),
}
