{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'echelle grating scattering table',
    'ld_tpn': 'stis_ech_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': '(DETECTOR != "CCD" and OBSTYPE == "SPECTROSCOPIC")',
    'suffix': 'ech',
    'text_descr': 'Echelle Scattering Table',
    'tpn': 'stis_ech.tpn',
    'unique_rowkeys': ('OPT_ELEM', 'SPORDER'),
}
