{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'echelle cross-dispersion scattering table',
    'ld_tpn': 'stis_exs_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': '(DETECTOR != "CCD" and OBSTYPE == "SPECTROSCOPIC")',
    'suffix': 'exs',
    'text_descr': 'Echelle Cross-Dispersion Scattering Table',
    'tpn': 'stis_exs.tpn',
    'unique_rowkeys': ('OPT_ELEM',),
}
