{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'template cal lamp spectra table',
    'ld_tpn': 'stis_lmp_ld.tpn',
    'parkey': (),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': '(OBSTYPE == "SPECTROSCOPIC")',
    'suffix': 'lmp',
    'text_descr': 'Template Calibration Lamp Spectra Table',
    'tpn': 'stis_lmp.tpn',
    'unique_rowkeys': ('LAMPSET', 'OPT_ELEM', 'SCLAMP'),
}
