{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': '2-d spectrum distortion correction table',
    'ld_tpn': 'stis_sdc_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': '(OBSTYPE == "SPECTROSCOPIC")',
    'suffix': 'sdc',
    'text_descr': '2-d Spectrum Distortion Corrections',
    'tpn': 'stis_sdc.tpn',
    'unique_rowkeys': ('APERTURE', 'OPT_ELEM', 'CENWAVE', 'SPORDER'),
}
