{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'mama offset correction table',
    'ld_tpn': 'stis_moc_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': '(DETECTOR != "CCD" and OBSTYPE == "SPECTROSCOPIC")',
    'suffix': 'moc',
    'text_descr': 'Mama Offset Correction Table',
    'tpn': 'stis_moc.tpn',
    'unique_rowkeys': ('OPT_ELEM', 'CENWAVE', 'SPORDER'),
}
