{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'cosmic ray rejection',
    'ld_tpn': 'wfc3_crr_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'crr',
    'text_descr': 'Cosmic Ray Rejection Parameter Table',
    'tpn': 'wfc3_crr.tpn',
    'unique_rowkeys': ('CRSPLIT', 'MEANEXP', 'CCDCHIP', 'SCALENSE', 'INITGUES', 'SKYSUB', 'CRSIGMAS', 'CRRADIUS', 'CRTHRESH', 'BADINPDQ', 'CRMASK'),
}
