{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'distortion coefficients',
    'ld_tpn': 'wfc3_idc_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'idc',
    'text_descr': 'Image Distortion Correction File',
    'tpn': 'wfc3_idc.tpn',
    'unique_rowkeys': ('CCDCHIP', 'FILTER', 'V2REF', 'V3REF', 'XSIZE', 'YSIZE'),
}
