{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'post flash',
    'ld_tpn': 'wfc3_fls_ld.tpn',
    'parkey': ('DETECTOR', 'CCDAMP', 'BINAXIS1', 'BINAXIS2', 'FLASHCUR', 'SHUTRPOS'),
    'parkey_relevance': {},
    'reffile_format': 'image',
    'reffile_required': 'none',
    'reffile_switch': 'flshcorr',
    'rmap_relevance': '((DETECTOR == "UVIS" and FLASHCUR != "ZERO") and (FLSHCORR != "OMIT"))',
    'suffix': 'fls',
    'text_descr': 'Post-flash Image',
    'tpn': 'wfc3_fls.tpn',
    'unique_rowkeys': None,
}
