{
    'extra_keys': (),
    'file_ext': '.r2h',
    'filetype': 'bas',
    'ld_tpn': 'wp2_bas_ld.tpn',
    'parkey': ('MODE', 'ATODGAIN'),
    'parkey_relevance': {},
    'reffile_format': 'image',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'bas',
    'text_descr': 'Bias Frame',
    'tpn': 'wp2_bas.tpn',
    'unique_rowkeys': None,
}
