{
    'extra_keys': ('imagetyp', 'filtnam1', 'filtnam2', 'lrfwave'),
    'file_ext': '.r4h',
    'filetype': 'flt',
    'ld_tpn': 'wp2_flt_ld.tpn',
    'parkey': ('MODE', 'FILTER1', 'FILTER2'),
    'parkey_relevance': {},
    'reffile_format': 'image',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'flt',
    'text_descr': 'Flat Field',
    'tpn': 'wp2_flt.tpn',
    'unique_rowkeys': None,
}
