#! /usr/bin/env python
#-*-python-*-
import sys
import os.path

from crds import pysh, log, utils

def main():
    pysh.usage("<refactor_test_output> <submit_dir>", 2, 2)	
    refactor = sys.argv[1]
    lines = pysh.lines("grep Reference ${refactor} | sort")
    for line in lines:
        words = line.split()
        rmap = words[4]
        cdbs_path = words[5]
        instrument, filekind = rmap.split("_")[1:3]
        filekind = filekind.split(".")[0]
        outpath = sys.argv[2] + "/" + instrument + "_" + filekind + \
            "/" + os.path.basename(cdbs_path)
        utils.ensure_dir_exists(outpath)
        pysh.sh("ln -s ${cdbs_path} ${outpath}")
        log.info("Linked", outpath)


if __name__ == "__main__":
    main()

