{
    'derived_from' : 'jwst_miri_photom_0002.rmap',
    'file_ext' : '.fits',
    'filekind' : 'PHOTOM',
    'filetype' : 'PHOTOMETRIC CALIBRATION',
    'instrument' : 'MIRI',
    'mapping' : 'REFERENCE',
    'name' : 'jwst_miri_photom_0003.rmap',
    'observatory' : 'JWST',
    'parkey' : (('META.INSTRUMENT.DETECTOR', 'META.INSTRUMENT.FILTER'),),
    'sha1sum' : 'c0e025d2c45a0bc1819f96545397a1580c830810',
    'suffix' : 'photom',
    'text_descr' : 'Absolute Calibration',
    'unique_rowkeys': ('FILTER', 'SUBARRAY', 'BAND'),
}
