{
    'derived_from' : 'jwst_niriss_photom_0002.rmap',
    'file_ext' : '.fits',
    'filekind' : 'PHOTOM',
    'filetype' : 'PHOTOMETRIC CALIBRATION',
    'instrument' : 'NIRISS',
    'mapping' : 'REFERENCE',
    'name' : 'jwst_niriss_photom_0003.rmap',
    'observatory' : 'JWST',
    'parkey' : (('META.INSTRUMENT.DETECTOR', 'META.INSTRUMENT.FILTER'),),
    'sha1sum' : 'cabd72cf325dc5bc2a52ff480de22090e0f35730',
    'suffix' : 'photom',
    'text_descr' : 'Absolute Calibration',
    'unique_rowkeys': ('FILTER', 'PUPIL', 'ORDER'),
}
