name: crds-latest-contexts
description: Retrieve latest context filenames for observatories using the Calibration Reference Data System (CRDS)
branding:
  icon: book-open
  color: black

inputs:
  require_hst:
    description: require response from Hubble Space Telescope CRDS server
    required: false
    default: "false"
  require_jwst:
    description: require response from James Webb Space Telescope CRDS server
    required: false
    default: "false"
  require_roman:
    description: require response from Nancy Grace Roman Space Telescope CRDS server
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - id: hst_crds
      env:
        OBSERVATORY: hst
        CRDS_SERVER_URL: https://hst-crds.stsci.edu
      run: >
        echo "context=$(
        curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ env.OBSERVATORY }}", "latest"], "id": 1}' ${{ env.CRDS_SERVER_URL }}/json/ --retry 8 --connect-timeout 10 |
        python -c "import sys, json; print(json.load(sys.stdin)['result'])"
        )" >> $GITHUB_OUTPUT
      shell: bash
    - if: inputs.require_hst
      run: if [[ ! -z "${{ steps.hst_crds.outputs.context }}" ]]; then echo ${{ steps.hst_crds.outputs.context }}; else exit 1; fi
      shell: bash
    - id: jwst_crds
      env:
        OBSERVATORY: jwst
        CRDS_SERVER_URL: https://jwst-crds.stsci.edu
      run: >
        echo "context=$(
        curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ env.OBSERVATORY }}", "latest"], "id": 1}' ${{ env.CRDS_SERVER_URL }}/json/ --retry 8 --connect-timeout 10 |
        python -c "import sys, json; print(json.load(sys.stdin)['result'])"
        )" >> $GITHUB_OUTPUT
      shell: bash
    - if: inputs.require_jwst
      run: if [[ ! -z "${{ steps.jwst_crds.outputs.context }}" ]]; then echo ${{ steps.jwst_crds.outputs.context }}; else exit 1; fi
      shell: bash
    - id: roman_crds
      env:
        OBSERVATORY: roman
        CRDS_SERVER_URL: https://roman-crds.stsci.edu
      run: >
        echo "context=$(
        curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ env.OBSERVATORY }}", "latest"], "id": 1}' ${{ env.CRDS_SERVER_URL }}/json/ --retry 8 |
        python -c "import sys, json; print(json.load(sys.stdin)['result'])"
        )" >> $GITHUB_OUTPUT
      shell: bash
    - if: inputs.require_roman
      run: if [[ ! -z "${{ steps.roman_crds.outputs.context }}" ]]; then echo ${{ steps.roman_crds.outputs.context }}; else exit 1; fi
      shell: bash

outputs:
  hst:
    description: latest CRDS context for the Hubble Space Telescope
    value: ${{ steps.hst_crds.outputs.context }}
  jwst:
    description: latest CRDS context for the James Webb Space Telescope
    value: ${{ steps.jwst_crds.outputs.context }}
  roman:
    description: latest CRDS context for the Nancy Grace Roman Space Telescope
    value: ${{ steps.roman_crds.outputs.context }}
