#! /bin/tcsh


rm ../cdbs.paths.gz
python -m crds.hst.locate   # regenerate cdbs.paths.gz
mv cdbs.paths.gz ..

../../install

# Header cache is regenerated automatically if nothing there to load.
rm header_cache

# Regenerate rmaps for all instruments, saving/caching reference header info
./gen_file_rmaps --save |& tee gen_file_rmaps.out

../../install

# Check test datasets,  saving/caching dataset header info
./tlookup ../../../testdata/acs/warren/*_raw.fits --save |& tee results.warren
./tlookup ../../../testdata/wfc3/howard/*_raw.fits --save |& tee results.howard
