export CRDS_SERVER_URL="https://roman-crds-serverless.stsci.edu"
export CRDS_PATH=${HOME}/crds_cache
export CRDS_S3_ENABLED=1
export CRDS_S3_RETURN_URI=0
export CRDS_S3_BUCKET=stpubdata
export CRDS_S3_PREFIX=/roman/crds
export CRDS_MAPPING_URI=s3://${CRDS_S3_BUCKET}${CRDS_S3_PREFIX}/mappings/roman
export CRDS_REFERENCE_URI=s3://${CRDS_S3_BUCKET}${CRDS_S3_PREFIX}/references/roman
export CRDS_CONFIG_URI=s3://${CRDS_S3_BUCKET}${CRDS_S3_PREFIX}/config/roman
export CRDS_USE_PICKLED_CONTEXTS=0
export CRDS_PICKLE_URI=s3://${CRDS_S3_BUCKET}${CRDS_S3_PREFIX}/pickles/${CRDS_OBSERVATORY}
export CRDS_DOWNLOAD_MODE=plugin
export CRDS_DOWNLOAD_PLUGIN='crds_s3_get ${FILENAME} -d ${OUTPUT_PATH} -s ${FILE_SIZE} -c ${FILE_SHA1SUM}'