#! /usr/bin/env python
#-*-python-*-

"""
Emits a simple .rst table given a rough dump of the table as space
delimited text lines.   Basically it figures out column widths and
reformats accordingly to line things up.   Adds leading and trailing
punctuator lines.
"""

import sys

linelen = {}

for line in open(sys.argv[1]):
    words = line.strip().split()
    for i, w in enumerate(words):
        if i in linelen:
            linelen[i] = max(linelen[i], len(w))
        else:
            linelen[i] = len(w)

format = ""
for i in range(len(linelen.keys())):
    format = format + "%-" + str(linelen[i]+1) + "s"

t = ()
for i in range(len(linelen.keys())):
    t = t + ("="*linelen[i],)

ls = open(sys.argv[1]).readlines()

print format % t
print format % tuple(ls[0].strip().split())
print format % t
for line in ls[1:]:
    print format % tuple(line.strip().split())
print format % t


