#! /usr/bin/env python
#-*-python-*-

"""Quick and dirty script to process HTML tables which have been
stripped down to something like this:

<tr>
 field1 words
 field2 units
 field3 junk
</tr>

into:

field1_words   field2_units   field3_junk

The underscore joined words of each field can then be easily processed
by the "justify" script to produce .rst

Joining underscores are then replaced with spaces again by hand.

"""

import sys, re

state = "outside"
row = ""

TR = re.compile("\s*<tr[^>]*>\s*")
TR_ = re.compile("\s*</tr>\s*")

for line in open(sys.argv[1]):
    if TR.match(line):
        state = "inside"
        row = ""
        continue
    elif TR_.match(line):
        state = "outside"
        print row
        continue
    if state == "inside":
        row = row + " " + line.strip().replace(" ","_")
    elif state == "outside":
        sys.stdout.write(line)
