#! /usr/bin/env python
#-*-python-*-

import sys, re

"""Quick and dirty script to process .rst-style links into out-of-line
markup which can be referred to with a "replacement link".

It processes:

   Chatting along discussing `the_link_<http://where.it.goes>`_  
   with more succinct markup which works a lot better in .rst tables.


into:

   Chatting along discussing |the_link|_ with more succinct markup which
   works a lot better in .rst tables.

"""

LINK = re.compile(r"`([^<]+)_<(http[^<>]+)>`_")

for line in open(sys.argv[1]):
    m = LINK.search(line)
    if m:
        print LINK.sub(r"|\1|_", line),
