#! /usr/bin/env python
#-*-python-*-

"""Quick and dirty script to process .rst-style links into out-of-line
markup which can be referred to with a "replacement link".

It processes:

   `the_link_<http://where.it.goes>`_  

into:

.. |the_link| replace:: the_link
.. _the_link: http:://where.it.goes

"""

import sys, re

LINK = re.compile(r".*`([^<]+)_<(http[^<>]+)>`_.*")

for line in open(sys.argv[1]):
    m = LINK.search(line)
    if m:
        print LINK.sub(r".. |\1|  replace:: \1", line)
        print LINK.sub(r".. _\1:  \2", line)
        print 
