#! /usr/bin/env python
#-*-python-*-

"""This script is used to iterate a base_command over all instruments applicable to the
specified context.   base_command is run in a subprocess for each instrument reducing
memory consumption to that of a single instrument.

usage: crds_instrument_iter  <base_command>  <context>  [remaining parameters...]

${context} and CONTEXT are replaced with <context>
${instrument and INSTRUMENT are replaced by the current instrument of the iteration.
"""

import sys

import crds
from crds import pysh, client

def main(args):
    
    base_command = args[1]
    
    if "operational" in args[2]:
        context = crds.get_default_context()
    else:
        context = args[2]
        
    client.dump_mappings(context)
        
    for instrument in crds.get_cached_mapping(context).selections:
        command = "${base_command} --new-context ${context} " + " ".join(args[3:])
        command = command.replace("CONTEXT", context)
        command = command.replace("INSTRUMENT", instrument)
        pysh.sh(command, trace_commands=True)

if __name__ == "__main__":
    pysh.usage("base_command context [...]", 1)
    main(sys.argv)

