{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'spot position table',
    'ld_tpn': 'acs_csp_ld.tpn',
    'parkey': ('DETECTOR', 'OBSTYPE'),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'no',
    'reffile_switch': 'none',
    'rmap_relevance': '(DETECTOR == "HRC" and OBSTYPE == "CORONAGRAPHIC")',
    'suffix': 'csp',
    'text_descr': 'Spot Position Table',
    'tpn': 'acs_csp.tpn',
    'unique_rowkeys': ('DATE',),
}
