{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'image photometry table',
    'ld_tpn': 'acs_imp_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'yes',
    'reffile_switch': 'photcorr',
    'rmap_relevance': '(PHOTCORR != "OMIT")',
    'suffix': 'imp',
    'text_descr': 'Photometry Keyword Table',
    'tpn': 'acs_imp.tpn',
    'unique_rowkeys': ('OBSMODE',),
}
