{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'spot flat',
    'ld_tpn': 'acs_cfl_ld.tpn',
    'parkey': ('DETECTOR', 'FILTER1', 'FILTER2', 'OBSTYPE'),
    'parkey_relevance': {},
    'reffile_format': 'image',
    'reffile_required': 'no',
    'reffile_switch': 'none',
    'rmap_relevance': '(DETECTOR == "HRC" and OBSTYPE == "CORONAGRAPHIC")',
    'suffix': 'cfl',
    'text_descr': 'Coronagraphic Spot Flat Image',
    'tpn': 'acs_cfl.tpn',
    'unique_rowkeys': None,
}
