{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'large scale flat',
    'ld_tpn': 'acs_lfl_ld.tpn',
    'parkey': ('DETECTOR', 'CCDAMP', 'CCDGAIN', 'FILTER1', 'FILTER2'),
    'parkey_relevance': {'ccdgain': '(DETECTOR != "SBC")', 'ccdamp': '(DETECTOR != "SBC")'},
    'reffile_format': 'image',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'lfl',
    'text_descr': 'Low-order Flat Field Image',
    'tpn': 'acs_lfl.tpn',
    'unique_rowkeys': None,
}
