{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'pixcte',
    'ld_tpn': 'acs_cte_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'no',
    'reffile_switch': 'pctecorr',
    'rmap_relevance': '((DETECTOR == "WFC") and (PCTECORR != "OMIT"))',
    'suffix': 'cte',
    'text_descr': 'Pixel CTE Correction Table',
    'tpn': 'acs_cte.tpn',
}
