{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'bad time intervals table',
    'ld_tpn': 'cos_badt_ld.tpn',
    'parkey': ('DETECTOR', 'OBSMODE'),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'badtcorr',
    'rmap_relevance': '((DETECTOR == "FUV" and OBSMODE == "TIME-TAG") and (BADTCORR != "OMIT"))',
    'suffix': 'badt',
    'text_descr': 'Bad Time Interval Table',
    'tpn': 'cos_badt.tpn',
    'unique_rowkeys': (),
}
