{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': '2d spectrum profile table',
    'ld_tpn': 'cos_profile_ld.tpn',
    'parkey': ('DETECTOR', 'OBSTYPE', 'LIFE_ADJ'),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'yes',
    'reffile_switch': 'algncorr',
    'rmap_relevance': '(LIFE_ADJ == "3.0")',
    'suffix': 'profile',
    'text_descr': '2D Spectrum Profile Table',
    'tpn': 'cos_profile.tpn',
    'unique_rowkeys': ('SEGMENT', 'OPT_ELEM', 'CENWAVE', 'APERTURE'),
}
