{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'deadtime reference table',
    'ld_tpn': 'cos_dead_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'deadcorr',
    'rmap_relevance': '(DEADCORR != "OMIT")',
    'suffix': 'dead',
    'text_descr': 'Deadtime Reference Table',
    'tpn': 'cos_dead.tpn',
    'unique_rowkeys': (),
}
