{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'zpr',
    'ld_tpn': 'nic_zpr_ld.tpn',
    'parkey': (),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'no',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'zpr',
    'text_descr': 'Nonlincor Zeropoint Scaling Table',
    'tpn': 'nic_zpr.tpn',
    'unique_rowkeys': ('PHOTMODE',),
}
