{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'idc',
    'ld_tpn': 'nic_idc_ld.tpn',
    'parkey': ('CAMERA',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'no',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'idc',
    'text_descr': 'Image Distortion Correction File',
    'tpn': 'nic_idc.tpn',
    'unique_rowkeys': ('DETCHIP', 'FILTER'),
}
