{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'pht',
    'ld_tpn': 'nic_pht_ld.tpn',
    'parkey': (),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'pht',
    'text_descr': 'Phototmetric Calibration Table',
    'tpn': 'nic_pht.tpn',
    'unique_rowkeys': ('PHOTMODE',),
}
