{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'incidence angle correction table',
    'ld_tpn': 'stis_iac_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': '(OBSTYPE == "SPECTROSCOPIC")',
    'suffix': 'iac',
    'text_descr': 'Incidence Angle Correction Table',
    'tpn': 'stis_iac.tpn',
    'unique_rowkeys': ('OPT_ELEM', 'SPORDER', 'CENWAVE'),
}
