{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'detector halo table',
    'ld_tpn': 'stis_hal_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': '(DETECTOR != "CCD" and OBSTYPE == "SPECTROSCOPIC")',
    'suffix': 'hal',
    'text_descr': 'Detectore Halo Table',
    'tpn': 'stis_hal.tpn',
    'unique_rowkeys': ('OPT_ELEM', 'HALOWAVE'),
}
