{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'dark image',
    'ld_tpn': 'stis_drk_ld.tpn',
    'parkey': ('DETECTOR', 'CCDAMP', 'CCDGAIN'),
    'parkey_relevance': {'ccdgain': '(DETECTOR == "CCD")', 'ccdamp': '(DETECTOR == "CCD")'},
    'reffile_format': 'image',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'drk',
    'text_descr': 'Dark Frame',
    'tpn': 'stis_drk.tpn',
    'unique_rowkeys': None,
}
