{
    'description' : '''
PR #79700,79701

Keyword: DRKCFILE

CTE Dark Image File (DRC): <uniquename>_drc.fits

Description: The CTE dark current reference image file consists of an image of
the dark signal (i.e., the signal generated by the detector in the absence of
photons from the sky) for use with CTE-corrected data.
This DRC file is for use in the CTE-correction branch of calwf3 only; non-CTE
corrected data use the DRK dark image.

Format: For WFC3/UVIS observations, the dark reference file is applied after
the CCD overscan regions are trimmed from the input science image, and
therefore the reference file must have its overscan regions trimmed off as
well. Thus the UVIS CTE dark image size is 2051 x 4096 for unbinned images
(again, there are no plans to provide CTE correction for binned or subarray
images). Calwf3 multiplies the dark image by the darktime keyword and divides
by the gain before subtracting it from the science image, so the UVIS dark
reference file must be in units of electrons per second. CTE dark reference
images for each of the 2 CCDs that make up the full UVIS detector array are
stored separately in 2 imsets in the dark file, identical to the UVIS science
data. There is no IR equivalent for the DRC file.

Selection criteria: The appropriate CTE dark reference file is selected by the
keywords DETECTOR, CCDAMP, APERTURE, BINAXIS1, BINAXIS2, and CHINJECT.

Restrictions: none

Required additional keywords: FILETYPE = 'CTEDARK'
''',
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'CTEDARK',
    'ld_tpn': 'wfc3_drc_ld.tpn',
    'parkey': ('DETECTOR', 'CCDAMP', 'APERTURE', 'BINAXIS1', 'BINAXIS2', 'CHINJECT'),
    'reffile_format': 'IMAGE',
    'reffile_required': 'none',
    'reffile_switch': 'PCTECORR',
    'rmap_relevance': '((DETECTOR == "UVIS") and (SUBARRAY == "FALSE"))',
    'suffix': 'drc',
    'text_descr': 'Cte Corrected Dark',
    'tpn': 'wfc3_drc.tpn',
    'unique_rowkeys': None,
}
