{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'shutter shading',
    'ld_tpn': 'wfc3_shd_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'image',
    'reffile_required': 'none',
    'reffile_switch': 'shadcorr',
    'rmap_relevance': '((DETECTOR == "UVIS") and (SHADCORR != "OMIT"))',
    'suffix': 'shd',
    'text_descr': 'Shutter Shading Correction Image',
    'tpn': 'wfc3_shd.tpn',
    'unique_rowkeys': None,
}
