{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'overscan',
    'ld_tpn': 'wfc3_osc_ld.tpn',
    'parkey': ('DETECTOR',),
    'parkey_relevance': {},
    'reffile_format': 'table',
    'reffile_required': 'none',
    'reffile_switch': 'none',
    'rmap_relevance': 'ALWAYS',
    'suffix': 'osc',
    'text_descr': 'Overscan Region Table',
    'tpn': 'wfc3_osc.tpn',
    'unique_rowkeys': ('CCDCHIP', 'CCDAMP', 'BINX', 'BINY', 'NX', 'NY'),
}
