{
    'extra_keys': (),
    'file_ext': '.fits',
    'filetype': 'dxy grid',
    'ld_tpn': 'wfc3_npl_ld.tpn',
    'parkey': ('DETECTOR', 'FILTER'),
    'parkey_relevance': {},
    'reffile_format': 'image',
    'reffile_required': 'no',
    'reffile_switch': 'drizcorr',
    'rmap_relevance': '((DETECTOR == "UVIS") and (DRIZCORR != "OMIT"))',
    'suffix': 'npl',
    'text_descr': 'Non-polynomial Offset',
    'tpn': 'wfc3_npl.tpn',
    'unique_rowkeys': None,
}
