#! /bin/csh -x

# This script runs on a local computer,  copying datasets to tufnel,  bestreffing them,  and copying them back.
# This prevents storage issues on tufnel.

foreach f ($*)
   set rootname=`basename $f _raw.fits`
   set dir=`dirname $f`
   foreach kind (_raw.fits _spt.fits _trl.fits _lrc.fits _lsp.fits)
      scp ${dir}/${rootname}${kind} tufnel:
   end
   ssh tufnel  ./bestref ${rootname}
   foreach kind (_raw.fits) #  _spt.fits _trl.fits _lrc.fits _lsp.fits)
      scp  tufnel:${rootname}${kind} ${dir}/${rootname}${kind}
   end
   foreach kind (_raw.fits _spt.fits _trl.fits _lrc.fits _lsp.fits)
      ssh tufnel rm ${rootname}${kind}
   end
end
