#! /bin/tcsh

rm -f ../../../datasets/opus_bestref.pkl  opus_bestrefs.err

./regen |& tee regen.out

./get_opus_bestref |& tee opus_bestrefs.err

mv testall.err testall.err.1

./testall >& testall.err.2
grep -E 'errors|warn|datasets' testall.err.2 | grep -v -E 'pickle'
mv *.stats ../../../stats
