#! /bin/tcsh

rm -f ../../../datasets/opus_bestref.pkl  opus_bestrefs.err

./regen |& tee regen.out

./get_opus_bestref testall.err.1 |& tee opus_bestrefs.err

./testall >& testall.err.2
grep -E 'errors|warn|datasets' testall.err.2 | grep -v -E 'pickle'

mv *.stats ../../../stats
