#! /usr/bin/env python
import sys

from crds import bestrefs, pysh

pysh.usage("[-d (dry-run, no updates)] <crds_context> <dataset_file(s)>...", 2, 10000)

DRY_RUN = False
if "-d" in sys.argv:
    sys.argv.remove("-d")
    DRY_RUN = True

pars = "--print-affected --new-context {} --files {} ".format(*sys.argv[1:3]) + " ".join(sys.argv[3:])
if not DRY_RUN:
    pars += " --update-bestrefs"

sys.exit(bestrefs.BestrefsScript(argv = pars)())

