name: contexts

on:
  workflow_call:
    outputs:
      hst:
        value: ${{ jobs.contexts.outputs.hst }}
      jwst:
        value: ${{ jobs.contexts.outputs.jwst }}
      roman:
        value: ${{ jobs.contexts.outputs.roman }}
  workflow_dispatch:

jobs:
  contexts:
    name: retrieve latest CRDS contexts
    runs-on: ubuntu-latest
    outputs:
      hst: ${{ steps.hst_crds_context.outputs.pmap }}
      jwst: ${{ steps.jwst_crds_context.outputs.pmap }}
      roman: ${{ steps.roman_crds_context.outputs.pmap }}
    steps:
      - id: hst_crds_context
        env:
          OBSERVATORY: hst
          CRDS_SERVER_URL: https://hst-crds.stsci.edu
        run: >
          echo "pmap=$(
          curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ env.OBSERVATORY }}"], "id": 1}' ${{ env.CRDS_SERVER_URL }}/json/ |
          python -c "import sys, json; print(json.load(sys.stdin)['result'])"
          )" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.hst_crds_context.outputs.pmap }}
      - id: jwst_crds_context
        env:
          OBSERVATORY: jwst
          CRDS_SERVER_URL: https://jwst-crds.stsci.edu
        run: >
          echo "pmap=$(
          curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ env.OBSERVATORY }}"], "id": 1}' ${{ env.CRDS_SERVER_URL }}/json/ |
          python -c "import sys, json; print(json.load(sys.stdin)['result'])"
          )" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.jwst_crds_context.outputs.pmap }}
      - id: roman_crds_context
        env:
          OBSERVATORY: roman
          CRDS_SERVER_URL: https://roman-crds.stsci.edu
        run: >
          echo "pmap=$(
          curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ env.OBSERVATORY }}"], "id": 1}' ${{ env.CRDS_SERVER_URL }}/json/ |
          python -c "import sys, json; print(json.load(sys.stdin)['result'])"
          )" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.roman_crds_context.outputs.pmap }}
