# TODO: deprecate this reusable workflow in favor of using the action
name: contexts

on:
  workflow_call:
    inputs:
      observatory:
        default: 'hst,jwst,roman'
        required: false
        type: string
    outputs:
      hst:
        value: ${{ jobs.contexts.outputs.hst }}
      jwst:
        value: ${{ jobs.contexts.outputs.jwst }}
      roman:
        value: ${{ jobs.contexts.outputs.roman }}
  workflow_dispatch:

jobs:
  contexts:
    name: retrieve latest CRDS contexts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: spacetelescope/crds
      - id: contexts
        uses: ./
        with:
          require_hst: ${{ contains(inputs.observatory, 'hst') }}
          require_jwst: ${{ contains(inputs.observatory, 'jwst') }}
          require_roman: ${{ contains(inputs.observatory, 'roman') }}
    outputs:
      hst: ${{ steps.contexts.outputs.hst }}
      jwst: ${{ steps.contexts.outputs.jwst }}
      roman: ${{ steps.contexts.outputs.roman }}
